### PR TITLE
go: a few minor tweaks

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

### CODE REVIEW

**Comment by mvdan** [comment]
I verified that the resulting package is still 134MiB and contains basically the same.

What's weird is that, every time I run `makepkg --nocheck --skippgpcheck -C`, I get a tar.zst file that differs very slightly in its file size. Diffoscope seems to point at timestamps. I'm not sure if I'm doing anything wrong to get so many different timestamps at every run.

**Comment by Foxboron** [comment]
>What's weird is that, every time I run makepkg --nocheck --skippgpcheck -C, I get a tar.zst file that differs very slightly in its file size. Diffoscope seems to point at timestamps. I'm not sure if I'm doing anything wrong to get so many different timestamps at every run.

This depends on quite a few thing. Your local `makepkg.conf` might not be the one we use for packages. This is why using `devtools` to build and test distributed packages are important.
https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot

Regarding the changes: I'll merge but I won't do a new package release as they seem to be mostly cleanups. They'll be used whenever there is a rebuild needed or a new version comes out :)

**Comment by mvdan** [comment]
> This depends on quite a few thing. Your local `makepkg.conf` might not be the one we use for packages. This is why using `devtools` to build and test distributed packages are important.
> https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot

Ah I see, thanks. I naively assumed that the default makepkg.conf would already give me locally-reproducible builds, akin to how `go build` gives the same binary in the same environment by default.


> Regarding the changes: I'll merge but I won't do a new package release as they seem to be mostly cleanups. They'll be used whenever there is a rebuild needed or a new version comes out :)

Sounds good. I have a few more minor tweaks in mind, so I can send a follow-up PR when you've merged this. Or if you prefer to keep this PR open for now, I can keep adding commits. I assumed smaller PRs would be easier for you.

**Comment by Foxboron** [comment]
Hmm, feel free to add commits to this pull-request. I'll merge it once I do a new go build :)

**Pull request merged**
